#!/usr/bin/env node

// Chris Joakim, Microsoft, 2017/11/14

var app = require('./app');

app.set('port', process.env.PORT || 80);

var server = app.listen(app.get('port'), function() {
  console.log('Express server listening on port ' + server.address().port);
});
